### ISSUE TITLE
Linux - NDI - Video decoder not found

### ISSUE THREAD

**Issue by berniel99** [DistroAV/DistroAV#1034]
I am stuggling to find out what is causing this message. 
![Screenshot from 2024-06-07 10-07-22](https://github.com/obs-ndi/obs-ndi/assets/19897176/565ece25-c92c-4ee7-b2cc-f73cbadb1d09)

I have installed the 6.0.1 driver (same behaviour as 6.0.0).

In order to make OBS not complain about "missing version 5 libraries" when the current version of the actual NDI driver is 6, I have added the following symbolic links.  In the log, however, it correctly shows that the version 6 library is loaded without error.
![Screenshot from 2024-06-07 10-11-51](https://github.com/obs-ndi/obs-ndi/assets/19897176/aaae435f-b13c-4c29-b32e-95ca1caaaab8)

This issue only comes about when I try to get the feed from my new PTZOptics Move SE camera, which has NDI included in the firmware.

When I try my iPhone with the OBS app running in NDI mode, it works without error.

So to clarify, the "source" is detected by in OBS but for some reason, cannot be displayed.  

I also have ffmpeg and the all the latest up-to-date drivers installed to decode and encode H264 and H265, so the message makes no sense.

The support at PTZOptics are not keen on helping people with Linux systems, so I am reaching out here to see if I can get this to work and perhaps help others in the process.

**Comment by maxkelley** [comment]
I'm having this issue as well on an NDI HX camera from AIDA... I know that this camera worked on OBS27 or 28 and NDI v4, but I just did a fresh Ubuntu 24.04 install with latest OBS (30.x something) and 4.13.2 obs-ndi.

Does anyone know what libraries the NDI runtime is looking for in order to decide the h264, and why it's not working?

**Comment by berniel99** [comment]
I currently believe that libndihx.so is missing in the SDK distributed by NewTek.  Since NewTek don't have a technical support that the public can converse with, I cannot confirm that this is the case.  In any case, doing string searches within the libraries that they provide suggests that this may be the case.  The observation that this error only appears when trying to decode HX content further confirms my hunch.

**Comment by maxkelley** [comment]
That's a bummer! I ended up rolling back to the older version of OBS and NDI v4 to get things working somewhat... Hopefully this can get resolved in newer versions.

**Comment by 0x4243** [comment]
Using Ubuntu 24.04, OBS Studio 30.2 and OBS-NDI 4.13.2 I get the same issue when trying to use NDI HX Capture on an iPad. If I use Ubuntu 22.04, everything else the same, it works fine. I'm not so sure this is a problem with a missing library in the SDK. Seems to be related more to the version of ffmpeg used.

**Comment by tellustheguru** [comment]
Same problem with Linux Mint 22...

**Comment by santomet** [comment]
I had issues with our app using NDI libs and found this issue. 
NDlibs needs FFMPEG v4 libs to work properly. Since Ubuntu 24 is now on FFMPEG v6, it just won't work. I'm glad it showed this message to you guys, in my app I just saw a massive memory leak.

So, installing ffmpeg from the U22 repo is not a good idea. However, thanks to @BtbN we can now find static libs builds for FFMPEG v4. All you need to do is copy these files to wherever your libs are (typically, on Ubuntu-based systems `/usr/lib/x86_64-linux-gnu/`). Do not forget to use `cp -a` to preserve linkage.

In the archive, I have removed base .so links so that it won't cause problems with system's libs

[FFMPEG v4 libs Linux x64](https://mega.nz/file/6mRQHT7a#nKo1BMC0Nt3CducUidxHpjnfGVN5i-76kb9ZkRmXF14)

**Comment by BtbN** [comment]
It's a real bad idea to copy library files into system directories. Specially something like ffmpeg.
That's a surefire way to break every part of your system that uses ffmpeg.

I'm also not providing any 4.4 binaries anymore, given how old it is at this point, so that mega link is not directly from me.
My builds also never had NDI enabled, given it's nonfree, and removed from ffmpeg.

**Comment by santomet** [comment]
1. Yes, it is a very bad idea. The point here is that unless guys from NDI/NewTek/Vizrt create a sane library that would work with their "NDI|HX" on the latest major LTS Linux distro, there is no better alternative AFAIK. The way I have proposed is a good tradeoff between system stability and functioning NDI HX. The libs can live right next to real system libs almost unnoticed (you do not rewrite newer libs).
2. Yes, I wouldn't use sw from random Mega links either. And yes, you are not building ffmpeg v4 anymore but luckily the history of Releases on GitHub is deep enough :) If anyone is interested: [BtbN autobuild-2023-12-31](https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2023-12-31-12-55/ffmpeg-n4.4.4-89-g25841e4f90-linux64-gpl-shared-4.4.tar.xz).
3. I tagged you because this is possible thanks to your builds that come without external dependencies.
4. Yes, ffmpeg and NDI have a history :) Apart from what you know already, some ffmpeg code was used in NDI v4 libs statically! (That is why NDI|HX works if you downgrade to NDI v4). And this issue is just another reason why I am working on partying ways with NDI for good. 

So again, thank you for your builds, I have been using these for a very long time :)

**Comment by Trouffman** [comment]
Closing this thread as this is not a DistroAV plugin.
This is either PTXOptics or NDI directly for support.

Be aware that the DistroAV plugin CAN decode NDI HX.

**Comment by capeath** [comment]
Has anyone found how to install this correctly on the current Debian base (Bookworm, U 24*, Mint 22)?  Are we needing to install Deb 11 based systems?

**Comment by martialgallorini** [comment]
interested in having any solution regarding this issue.

thanks !

**Comment by capeath** [comment]
Hey.  I haven't found a solution.  There is a download that someone used to put FFMPEG4 next to the v6.  I haven't figured it out.  What I did was install Mint 21.3.  The Ubuntu PPA still supports Mint 21.3 unofficially (Mint is always unofficially supported).  I used the older drivers from NDI (version 5 I think).  This got everything working again.  21.3 is supported until 2027.  After that, we may have to budget SDI or HDMI cables and capture devices depending on cable length.  I really don't like that as the camera was purchased because of the NDI, but pettiness of others can cause issues for the rest.Good Luck and God BlessEric
        
        
          On Dec 2 2024, at 6:56 am, Martial ***@***.***> wrote:
          
        
        
           
interested in having any solution regarding this issue.
thanks !

**Comment by kgroeneveld** [comment]
I also faced that dreaded "NDI Video Decoder not found" image recently.

In my setup I am using kubuntu 24.04 with OBS 31.0. I tried various versions of DistroAV but ended up on 6.0.0. I also built my own binaries for DistroAV.

An additional issue I had is that with NDI SDK 6.1, OBS/DistroAV would always crash. Even the examples that came with NDI SDK would always crash. And it seems you can no longer download SDK 6.0 so I was unable to try that version. But I was able to download NDI SDK 5.6.1 which still seems to work fine with DistroAV 6.0.

You can search the the `libndi.so.5.6.1` library to see which version of FFmpeg it is looking for:

```
$ strings libndi.so.5.6.1 | grep 'libav' 
libavahi-common.so.3 
libavahi-client.so.3 
libavcodec.so.58 
libavcodec-ndi.so.58 
libavutil.so.56 
libavutil-ndi.so.56 
```

On the FFmpeg download page https://www.ffmpeg.org/download.html you can see the last version to use `libavcodec.so.58` and `libavutil.so.56` was FFmpeg 4.4.5. To build and install this version you can do something like the following:

``` 
sudo apt install build-essential libx264-dev nasm 
git clone https://git.ffmpeg.org/ffmpeg.git 
cd ffmpeg 
git checkout n4.4.5 
./configure --enable-gpl --enable-libx264 --enable-shared --disable-static 
make -j12 
DESTDIR=staging make install 
cd staging/usr/local/lib 
sudo cp -v `ls | grep '\.so.[0-9]*$'` /usr/local/lib 
sudo ldconfig 
```

After this I could finally stream video from my PTZOptics camera via NDI!

I think the above installs all the required packages on ubuntu 24.04, but I may have missed some. If you get an error there may be a missing package.

You could probably come up with a much more complex `configure` command to strip out lots of stuff you do not need, but I didn't bother trying.

The `cp` command above only copies the `libxxx.so.xx` files to `/usr/local/lib` and not the symlinks such as the non versioned `libxxx.so` files. If the non versioned symlinks were also copied it would likely break other things on your system that use FFmpeg.

Also interesting is that if you use a similar `strings` command on the NDI 6.1 libraries it contains references to multiple versions of FFmpeg. So I suspect it would be more forgiving on which version of FFmpeg is on your system. But since 6.1 always crashed for me I could not verify that.

I hope the above is helpful for someone.

Thank you DistroAV devs, it is a fantastic plugin to have available. It seems it should be a stock part of OBS.

**Comment by alexpokotilo** [comment]
--enable-gpl --enable-libx264 params are useless because we just need h264 decoding but these params added useless encoder

**Comment by RayneYoruka** [comment]
There shouldn't be any need for any of this anymore as NDI has updated their ffmpeg requirements in the begining of the year
> FFmpeg >= 7.0 is required for NDI HX to work on Linux


https://github.com/DistroAV/DistroAV/wiki/1.-Installation#linux-1

**Comment by alexpokotilo** [comment]
It's more than actual now, as not all Linuxes shipped with needed ffmpeg version. So in case if OS ffmpeg version doesn't match with need NDI version, @kgroeneveld instruction works great with some possible changes in ffmpeg version checkout. As NDI doesn't ship with embedded ffmpeg version(it can technically as it just need x264 decoder for HX decoding), you can always face with the case when ffmpeg version needed by NDI doesn't match with version provided by OS. If NDI start using ffmpeg library prefixes and deliver needed ffmpeg libs with its own .so files , this will fix the problem completely. But if not, this instruction will always be actual for HX decoding

**Comment by RayneYoruka** [comment]
> It's more than actual now, as not all Linuxes shipped with needed ffmpeg version. So in case if OS ffmpeg version doesn't match with need NDI version, [@kgroeneveld](https://github.com/kgroeneveld) instruction works great with some possible changes in ffmpeg version checkout. As NDI doesn't ship with embedded ffmpeg version(it can technically as it just need x264 decoder for HX decoding), you can always face with the case when ffmpeg version needed by NDI doesn't match with version provided by OS. If NDI start using ffmpeg library prefixes and deliver needed ffmpeg libs with its own .so files , this will fix the problem completely. But if not, this instruction will always be actual for HX decoding

NDI has had changed and will continue to change as its needed. Deprecated solutions pose a risk and that is why these are written on the wiki.

**Comment by DrNI** [comment]
I would be grateful if somebody could fix this with a version of DistroAV that is easy to install, without compiling things.

I'm on Ubuntu Studio 24.04, OBS 32.0.0, NDI SDK 6.2.1.0, DistroAV 6.1.1, ffmpeg is 6.1.1.

Let me point out why the issue is quite unfortunate: Quite some modern NDI hardware, such as the affordable Z Cam E2N camera delivers NDI HX3 only. Another example: The ZowieBox encoder that can do HX1 to HX3, but not Full NDI.

Especially now that Windows 10 support gets trashed, people with older but still powerful hardware who are on a budget could build an affordable video streaming solution with NDI and OBS on Linux. But due to this limitation, they simply can't. Because in order to do so, you'd need an OBS/DistroAV that can decode whatever comes in via NDI.

People who have an unlimited budget however won't even touch OBS, they will go for the Tricaster NDI switcher, vMix or similar.

Furthermore, since there are no NDI Tools for Linux, OBS is the only way to actually get something with NDI working on Linux anyways.

**Comment by Trouffman** [comment]
The requirement by NDI are controlled by... NDI.
Which ffmpeg version ships with which linux distro is controlled by... the Linux distros.

DistroAV (the implementation of NDI in OBS) does not have control over NDI technical choice, nor the ffmpeg version on the linux distros.

This is one of the reason to use the flatpak on linux, because this is usually easier to maintain.


**Long story short & definitive point is **
> If you want to decode NDI HX on Linux (whatever the distro/version), you **must** use ffmpeg 7 or higher (required by NDI)
> Using older SDK or plugin version is not supported by either NDI nor DistroAV.
