### ISSUE TITLE
[Feature]: Automatically uninstall obs-ndi with the MacOS installer.

### ISSUE THREAD

**Issue by jaminmc** [DistroAV/DistroAV#1097]
I noticed that there are no installation scripts in the macOS installer... A simple Postinstall script like this would automatically remove the obs-ndi plugin.

```bash
#!/bin/bash

# Define user and system plugin paths
PLUGIN_PATHS=(
  "$HOME/Library/Application Support/obs-studio/plugins/obs-ndi.plugin"
  "$HOME/Library/Application Support/obs-studio/plugins/obs-ndi.plugin.dSYM"
  "/Library/Application Support/obs-studio/plugins/obs-ndi.plugin"
  "/Library/Application Support/obs-studio/plugins/obs-ndi.plugin.dSYM"
)

# Function to remove a file or directory if it exists
remove_if_exists() {
  local path="$1"
  local use_sudo="$2"

  if [ -e "$path" ]; then
    echo "Removing $path..."
    if [ "$use_sudo" = true ]; then
      sudo rm -rf "$path"
    else
      rm -rf "$path"
    fi

    if [ $? -eq 0 ]; then
      echo "Successfully removed $path"
    else
      echo "Failed to remove $path"
    fi
  else
    echo "$path does not exist, skipping..."
  fi
}

# Loop through paths and remove them
for path in "${PLUGIN_PATHS[@]}"; do
  if [[ "$path" == "/Library/"* ]]; then
    remove_if_exists "$path" true
  else
    remove_if_exists "$path" false
  fi
done

exit 0
```

**Comment by paulpv** [comment]
DistroAV is based on
https://github.com/obsproject/obs-plugintemplate

We mostly just do whatever they do. 
They have no uninstall for their MacOS template. 
So we don't either. 

If this is a big problem then I recommend creating an Issue in their repo and once implemented we will pick it up. 

I am trying to avoid adding more one-off bespoke scripts than we already have. 
We had one for installing the Linux runtime because that is required. 

If you want to uninstall on Linux or MacOS then just follow these instructions: 
https://github.com/DistroAV/DistroAV/wiki/1.-Installation#uninstall

Yes, those instructions need to be updated for the obs-ndi to DistroAV rename.
It is a public wiki page. 
Anyone can edit it to fix it. 

Closing Won't Fix
