### ISSUE TITLE
Feature Request: HX2 toggle selection for NDI output/NDI Source

### ISSUE THREAD

**Issue by ravenium** [DistroAV/DistroAV#506]
Admittedly I am not sure if this is possible, or possibly I am misunderstanding how the NDI plugin works.  Given that HX2 seems to be NewTek's solution for NDI over WAN (greatly reduced bandwidth, at least), is it possible to have a toggle checkbox for the NDI plugin to have it transmit using HX2?  

This would allow OBS setups similar to Sienna TV's cloud solution.

**Comment by walterav1984** [comment]
Probably dependent on GPU realtime h264/h265 encoders so only available on selected Intel/Amd/Nvidia hardware acompanied with their driver(suites). Still a nice feature but for multiplatform OS support which OBS-Studio and obs-ndi is focussed it will take real effort to make a toggle button to let obs-ndi send hx2 instead of hx or normal ndi on all different OS and drivers.

**Comment by ravenium** [comment]
@walterav1984 I can definitely see how it would bring complexity to an otherwise fabulous "it just works" plugin.  It's worth noting that OBS supports nvenc (albeit that may be a shiny wrapper over its ffmpeg underpinnings), so there may be some system commonality that could be leveraged.

If sending it is not in the SDK though, they'd be stuck (I know receiving is as I've sent NDI HX camera sources to OBS).

Probably just my cloud rantings, but the bandwidth savings would be huge for smaller streamers with remote components (sienna.tv being a bit out of our price range).

**Comment by Trouffman** [comment]
Merging this with PR and issue up to date.

This cannot be done for now. But there is a PR "placeholder" for this .

https://github.com/DistroAV/DistroAV/pull/738
