### ISSUE TITLE
Camera through NDI

### ISSUE THREAD

**Issue by massatt212** [DistroAV/DistroAV#545]
Sending Webcam through NDI uses a lot of CPU, any solutions

**Comment by nettings** [comment]
Yes. Write a meaningful bug report that gives all the required information, let us know how much "a lot" is, and try to think before firing off random bug reports.
A shot in the dark: if your webcam is very noisy because of low light, that can cause a lot of extra work for a video codec. Don't know how badly it would affect NDI, though.
