### ISSUE TITLE
OBS NDI plugin causes growing latency

### ISSUE THREAD

**Issue by streamfuchs** [DistroAV/DistroAV#667]
Hi everyone,

I have got a problem with the intergration oft the obs-ndi plugin which might have been discussed already, I am not shure:

I did a streaming event 3 months ago with an USB-Camera I extendend with an UTN (USB to Network) –Server and a dedicated audio mixer connected to my computer via USB (operated with the ASIO-pluginfor OBS)

I adjusted the audiolatency in my audiomixer to match the latency of the camera, everything worked fine.
I added a second camera to my setup for a streaming event I had to do 3 days ago.
This camera is a PTZ-camera operated via NDI.

I used the OBS-NDI plugin (Windows 4.9.0) and added 80ms delay within OBS for that source to match my timing.
During my transmission I got aware of the fact that the NDI-camera run out of audio/video synchronisation.
After the transmission I did some tests with the following result:

When starting OBS everthing is in sync.
**During operation the NDI-Source (camera) has a shift of about 40ms every 10min. of operation.
So after 3 hours of operation my NDI-camera is about 720ms late which of course is not usable.**

Evertime I change the sync for the NDI-camera from source timing to network or from network to source timing the camera is back in sync again.
Obviously that shifting latency is an issue of the OBS-NDI plugin.
Does anyone out there made the same experiences as I did and is there a solution/workaround?
Of course it is not a solution to resync the camera every 5 minutes, especially when the camera is on air.
The best solution of course wouldbe a solution within the plugin.
Any ideas or advices?

**Comment by weitheiml** [comment]
Same problem here on OBS Mac 26 and 27 (OSX10.16) with the NDI Plugin and two different PTZ Cams. Syncing and applying different render-delays to lock pictures reliably is impossible. Switching scenes/cams seems to reset the delay, but a split-screen with both cameras reveals, that the delay is kind of random and not reproduceable.

**Comment by dingus9** [comment]
We run 3 NDI PTZ cameras, 1 hdi in bmd capture card and audio in from a dac. We delay the audio/hdmi video by 500ms to help account for the ndi delay. Delay seems to come and go at random. We arent able to replicate well 1 camera (ptzoptics) rarely drufts more then 10ms but the datavideo cameras are all over the place sometimes. also changing timing modes seems to help... Its better in the final product with the arbitrary 500ms delay though... Probably indicating that the ndi sources never exceed that much delay allowing obs to sync streams during encoding? Live view looks horribly out of sync but final product on destination seems synced for the most part... Until its not then idk how to fix! Thoughts?

**Comment by Avidjeff** [comment]
(Sorry in advance that this post is not very technical). I have been having the same issue with growing latency with NDI video output using OBS. 

To clarify, the issue is not audio / video syncing but a growing latency issue with OBS program output to local TV monitors via HDMI within a house of worship venue. 

When starting up OBS, the output lag is acceptable but it slowly becomes more apparent the longer OBS is open.  I have tried two computers, both running on Windows 10.  The first is a Lenovo i5 laptop, 8GB RAM and the second (new PC) is a micro desktop HP model using an i7 processor with an Invidia T1000 GPU and 16GB RAM.  Both PC's exhibit the same issue.  

 I use three PTZ NDI cameras (AlfaTron ALF-20NDIC).  For testing purposes, I added a  LC922x Logitech USB camera which never seems to display any appreciable video lag.  
 
All three Alfatron NDI PTZ cameras display slightly longer lag than the USB camera (which is acceptable) UNTIL about 30 minutes into using OBS.  (The video lag seems to slowly increase over time).  Trying to rule out any PC processor issues, I opened task manager and shut down all other background apps. Later, I upgraded the computer and still no success.  I would greatly appreciate any help with finding a solution!

**Comment by normen** [comment]
I am getting the same issue with the gstreamer plugin and RTSP streams, so maybe this issue is in OBS or in how (some) plugins deliver the frames?

**Comment by kinofuentes** [comment]
Any fixes found ? i got the same issue when i start obs on my gaming pc tha audio is fine on the stream pc but then overtime it starts desync and i need to restart obs on the gaming pc if you have any fix ill love to know it

**Comment by ogmkp** [comment]
Same problem here on Linux. there is no image or sound latency in the OBS internal output (encoder), just the monitoring from NDI to pipewire-pulse which shifts as it goes along (the problem doesn't exist for other sources such as mic In or media source).

**Comment by ogmkp** [comment]
Found on my side, enabling framesync causes constant sound delay on monitoring, so it's not related to this ticket which was opened before this feature.

**Comment by Maeldu83** [comment]
Hello guys,
Did you fix this ? I think I have the same issue 

thanks a lot

**Comment by streamfuchs** [comment]
Hi,

unfortunately I never got this issue solved.
With VMIX e.g. this is not a problem at all with NDI-sources.

Best regards

**Comment by Maeldu83** [comment]
Hi! 
thanks a lot for your answer :) 
Yeah, same with Vmix there is no issue … but I don’t want to use Vmix, I prefer OBS so this gets me mad ! 
also I found that on some PCs there isn’t this issue but I don’t know why. I’ll maybe try changing my motherboard.

**Comment by BitRate27** [comment]
@Maeldu83 @streamfuchs I have been seeing the same problem on my setup for a while now. I thought it may be because I didn't have my NDI timing setup correctly. Last week I turned on NTP on all cameras and changed the Audio/Video Sync to Network in the NDI source for each of these cameras. I still see a shift in delay as the streams progress over an hour. Will try and add some timing info to my logs in hopes of narrowing down the problem. Curious what your CPU % during streaming gets up to. Seems if mine gets above 30% things get a little weird.

**Comment by ogmkp** [comment]
I think it's not a problem of NDI timing, it's a problem of buffer recalculation by OBS see: #851

**Comment by paulpv** [comment]
Try the new DistroAV 6.0 pre-release build
https://github.com/DistroAV/DistroAV/releases/tag/6.0.0

**Comment by paulpv** [comment]
> I think it's not a problem of NDI timing, it's a problem of buffer recalculation by OBS see: #851

#851 was merged 2023/11/07 https://github.com/DistroAV/DistroAV/pull/867 and should be in all releases since then

**Comment by carryduff-fpc** [comment]
Is anyone still getting this issue? We are having the same issue with an increase in latency over time up to 750ms. I can ping the camera while streaming and it says 0ms ping rate so the network seems fine. Everything is up to date with regards drivers, distroAV, ndi6, win11.

**Comment by RayneYoruka** [comment]
> Is anyone still getting this issue? We are having the same issue with an increase in latency over time up to 750ms. I can ping the camera while streaming and it says 0ms ping rate so the network seems fine. Everything is up to date with regards drivers, distroAV, ndi6, win11.

Most of the discussion about NDI HX latency drifting overtime can be read here.  https://github.com/DistroAV/DistroAV/issues/851

Let's not revive old threads.
