### ISSUE TITLE
OBS-NDI rewrite alpha- green tint on capture. 

### ISSUE THREAD

**Issue by RAMChYLD** [DistroAV/DistroAV#768]
##### Issue type

- Bug report

##### Description
Arch upgraded to OBS 28.0.2 today so I set off repackaging the NDI libraries and obs-ndi for Arch. 

Upon testing, I noticed that the plugin was sending the signal with a very strong green tint. 

I initially used the same binaries I packaged for Ubuntu, but have tried rebuilding the binary natively in Arch for troubleshooting.

I have also tried switching between VAAPI and x264 thinking it's a hardware encoder issue, but to no avail. 

I have tried switching between Wayland and X11 but to no avail. 

The issue is not occurring with other input streams, so it appears that it's unique to Arch. 

##### Steps to reproduce and other useful info
Install libndi dependencies using custom-made package (to /usr/local/lib, just in case)
Install obs-ndi plugin using custom-made package
Start OBS. 

##### Technical information
- **Operating System:** Arch Linux x86-64 
- **OBS Studio Version:** 28.0.2-1 
- **obs-ndi Version:** alpha git 81a1612

##### Development Environment
GCC 12.2 
Cmake 3.24.2
libobs: 28.0,2, present at /usr/include/obs
Qt6: 6.3.2
libndi: 5.5.1

**Comment by RAMChYLD** [comment]
Update: Upgraded Windows to 28.0.2, NDI 5.5.1 and OBS-NDI rewrite and I'm having the green tint issue now too. Not having a good day.

**Comment by RAMChYLD** [comment]
Update 4: Found the fix or at least a workaround, at least on Arch Linux. I had my color space set to Rec. 709 because I found it provides additional brightness. On OBS 27.2.4 and earlier this is handled gracefully, but on OBS 28.0.0 and later it causes the green tint. I'm going to upgrade my windows machine back to 28.0.2 and change the settings and see if this also fixes things.

**Comment by songswell** [comment]
Hello, yesterday after loading OBS plug-in for I noticed my NDI output on 10bit OLED monitor set to sRGB had green tint.  If moved over to 8bit monitor looked normal. Image was a composite made on NukeX with alpha.  Nuke recently created monitor out with NDI plugin. Currently this NDI has no advanced color space options.  The reason I'm interested in this issue is I'm trying to bring a live AlexaMini arriraw stream into nuke with Unreal Engine then attach a Filmlight color node and do a live professional color correction ....... then broadcast the output with OBS.

**Comment by paulpv** [comment]
Try this in the latest `develop` branch `4.11.0-RC` tagged version that is due to officially release once approved: https://github.com/Palakis/obs-ndi/pull/849
