### ISSUE TITLE
[Bug]: Remote NDI sources not listed

### ISSUE THREAD

**Issue by sparrowme** [DistroAV/DistroAV#903]
### Operating System Version

Ubuntu 22.04.2 LTS

### OBS Version

29.1.3

### NDI Tools Version

NDI Runtime 5 is installed for Linux per README

### Describe the bug

This setup is 2 Identically installed OS/OBS/NDI versions.  

Both systems have the OBS system NDI Output settings enabled with Main checked and labeled OBS.

YES: This sounds like a firewall problem, but it is not. See testing/troubleshooting below.

Problem: Remote NDI Sources are not detected over the network (10.0.0.0/24)

### Steps to reproduce

1. Install OBS 29.1.3
2. Install NDI Runtime driver
3. Start OBS and enable NDI output from menu.
4. Add an NDI source from either machine
5. Note that only local Sources are seen

### Expected behavior

Remote NDI Sources should be shown in OBS

## Systems
**stream** is an HP Z820
**zbook** in an HP zbook 15

## What appears to work
Both systems can see (ONLY) themselves if I add an NDI source in OBS.  The main stream is available in the respective dropdown. And if I add additional Scene outputs/captures (with the NDI Output filter), those will also show up only locally in each list.

## Testing/Troubleshooting
- I installed Wireshark on both system to trace the udp 5353 traffic.
- Both systems show the expected output from **stream** in Wireshark.
- The MDNS broadcast shows the available NDI sources from **stream** being sent on BOTH **stream** and **zbook**.  They show identical packets.  (So not firewall)
- Starting OBS on **zbook** shows no packets on either system.  So even the local Wireshark is not detecting packets from OBS.  

I tried the ndi-python package from https://pypi.org/project/ndi-python/ to try some additional testing on **zbook**.  After getting it to compile pointing the compiler to the same ndisdk from the install instructions in this README, I run:
```
python examples\find.py
```

And get the output:
```
Network sources (2 found).
1. ZBOOK (Dedicated NDI Output)
2. ZBOOK (OBS)
```

So it follows that the NDI runtime with python does, in fact, see the same broadcast list that OBS sees.  I am not sure this test added anything valuable.  But what I can't understand is the fact that Wireshark on **zbook** CAN see the **stream** NDI outputs (packets), but the local **zbook** NDI runtime isn't picking them up.  Something seems... blocked :shrug:

**Comment by paulpv** [comment]
@sparrowme Thanks for that. I think it is indeed related to #896, but the problem is that I have no idea how any of obs-ndi's calls to the NDI sdk can result in this.

In my opinion and perspective, NDI is 100% responsible for abstracting out all of the network gotchas.
We just use their API to discover NDI sources and then show them.
The code is at:
https://github.com/obs-ndi/obs-ndi/blob/4daba126d0fc294a9f38213d9fb0a5a6b914c4ee/src/plugin-main.cpp#L119-L122
https://github.com/obs-ndi/obs-ndi/blob/4daba126d0fc294a9f38213d9fb0a5a6b914c4ee/src/obs-ndi-source.cpp#L183-L195

There is little to nothing I can think of that would make this present more reliably.
The NDI SDK documentation says:
![image](https://github.com/obs-ndi/obs-ndi/assets/1393897/5a29d19b-9e4d-4b3e-bb53-e5d0089e3e9f)

That last sentence is precisely what obs-ndi's above code does.

**Comment by paulpv** [comment]
Is this still an issue using 4.13.0?

**Comment by eliumoraes** [comment]
I was having that issue too! Fixed it with these steps:

1. Remove the old OBS setup and it's dependencies.

2. Install OBS via Flatpak
`flatpak install flathub com.obsproject.Studio`

3. Grab the NDI plugin via Flatpak
`flatpak install flathub com.obsproject.Studio.Plugin.NDI`

4. Launch OBS to check if everything is in place
`flatpak run com.obsproject.Studio`

5. In OBS, go to `Tools` > `NDI™ Output Settings` to ensure the NDI plugin is active.

Hope this helps anyone else facing the same problem!
