### ISSUE TITLE
Virustotal: 5 findings in current .exe

### ISSUE THREAD

**Issue by AcdNrg** [DistroAV/DistroAV#989]
As Win11 did not run the installer without complaining, I submitted the latest .exe installer to virustotal and get 5 findings of Trojan like behaviour: 

https://www.virustotal.com/gui/file/a73f34baea9b3739fa501b7311cd00cd24ad243755e6081c24e7996141b671ea

Please advise.

**Comment by Trouffman** [comment]
I have similar result when building on my machine as well. This is mostly a false positive. We will need to digg into which part of the code is getting this triggered.

**Comment by paulpv** [comment]
I wish I could explain them.
I know in the past we had a silly false positive because some obsplugin-template config used `http://www.mywebsite.com` as an example placeholder, but that innocent example in the was actually a virus site.
https://github.com/obsproject/obs-plugintemplate/issues/70

Could be something similarly innocent?

**Comment by ipkpjersi** [comment]
FWIW, when I saw this it was down to 2 out of 72, and re-analyzed it just now with it at 3 out of 73 (number of detections vs total number of AVs matters), indicating it's probably a false positive that got updated from at least a couple scanners. Also, the 3 AV's that picked it up aren't exactly the most prestegious and well-respected, they aren't the most trustworthy to begin with (you can look up reviews of them, they seem to be known for false positives).

I've dealt with similar issues in the past as a developer, in a Java app (jar file) I built before I literally had a single class variable get picked up as a "virus" in 4 out of 70 scanners, I moved it to a local variable and then the detections went away. The Java bytecode looked fine with a class variable and looked fine with a local variable too. Since that happened, I lost some trust in AVs lol

It's worth keeping an eye on, but I probably wouldn't worry too much about it.

**Comment by Trouffman** [comment]
Yep it's likely a false positive. We do not yet have the certificate to sign the install but this will be the case at some point.
